repos:
- repo: https://github.com/aws-cloudformation/cfn-lint
  rev: v0.71.1  # The version of cfn-lint to use
  hooks:
    - id: cfn-lint-rc
- repo: https://github.com/PyCQA/bandit
  rev: 1.7.4
  hooks:
    - id: bandit
      args: ["-r", "secure_keygen"]
      language_version: python3.9
- repo: https://github.com/psf/black
  rev: 22.10.0
  hooks:
    - id: black
      args: ["--line-length", "119"]
      language_version: python3.9
- repo: https://github.com/AleksaC/mirrors-cfn-nag
  rev: v0.8.9
  hooks:
   - id: cfn-nag
     files: template.yaml
